[package]
name = "basil"
version = "2026.8.19"
edition = "2024"
description = "A log aggregation and monitoring solution"
homepage = "https://github.com/saturn-xiv/basil"

[profile.release]
lto = true
strip = true

[dependencies]
chrono = "0.4"
log = "0.4"
axum = "0.8"
env_logger = "0.11"
askama = "0.16"
hyper = "1"
toml = "1"
data-encoding = "2"
opensearch = "2"

[dependencies.tower-http]
version = "0.7"
features = ["fs"]

[dependencies.reqwest]
version = "0.13"
features = ["json"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.uuid]
version = "1"
features = ["v4"]

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.jsonwebtoken]
version = "11"
features = ["rust_crypto"]

[dependencies.openssl-sys]
version = "*"
features = ["vendored"]
