[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "basil"
version = "2026.8.26"
authors = [{ name = "Jeremy Zheng", email = "jitang.zheng@gmail.com" }]
description = "A log aggregation and monitoring solution"
readme = "README.md"
requires-python = ">=3.14"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICENSE"]

dependencies = ["flask", "sqlalchemy", "pika", "opensearch-py", "pynacl"]

[project.urls]
Homepage = "https://github.com/saturn-xiv/basil"
Issues = "https://github.com/saturn-xiv/basil/issues"

[project.scripts]
basil = "basil:main"

[tool.pyright]
include = ["src"]
exclude = ["**/__pycache__", "tmp"]
venvPath = "."
venv = "tmp/python3"
pythonVersion = "3.14"
typeCheckingMode = "basic"
